name: src
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  toml: ^0.13.1
  path: ^1.8.0
  meta: ^1.9.0
  args: ^2.4.0
  xml: ^6.2.2
  console: ^4.1.0
  version: ^3.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
